name            = "skillloc"
main            = "worker.js"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding       = "DB"
database_name = "skillloc"
database_id   = "47559fa3-da8b-4230-bf4c-043991470031"
